import { createRentalRequestAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { SiteShell } from "@/components/site-shell";
import { getVehicles } from "@/lib/data";
import { formatCurrency } from "@/lib/utils";

type SearchParams=Promise<{vehicle?:string;sent?:string;error?:string}>;
export const dynamic="force-dynamic";
export default async function RentalRequestPage({searchParams}:{searchParams:SearchParams}){const params=await searchParams;const vehicles=await getVehicles({listingType:"rental",published:true});return <SiteShell><section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Rental request</p><h1>Plan your StepOne rental.</h1><p>Choose the vehicle and dates. No payment is taken online.</p></div></div><Flash sent={params.sent} error={params.error}/><form action={createRentalRequestAction} className="panel form-grid"><input type="hidden" name="return_to" value="/rentals/request"/><div className="field field-full"><label>Vehicle</label><select name="vehicle_id" defaultValue={params.vehicle??vehicles[0]?.id} required>{vehicles.map(v=><option key={v.id} value={v.id}>{v.year} {v.make} {v.model} — {formatCurrency(v.daily_rate)}/day</option>)}</select></div><div className="field"><label>Pickup date</label><input name="pickup_date" type="date" required/></div><div className="field"><label>Pickup time</label><input name="pickup_time" type="time" defaultValue="09:00" required/></div><div className="field"><label>Return date</label><input name="return_date" type="date" required/></div><div className="field"><label>Return time</label><input name="return_time" type="time" defaultValue="17:00" required/></div><div className="field field-full"><label>Pickup location</label><input name="pickup_location" defaultValue="Kilimani, Nairobi" required/></div><div className="field"><label>Full name</label><input name="full_name" required/></div><div className="field"><label>Phone</label><input name="phone" required/></div><div className="field"><label>Email</label><input name="email" type="email"/></div><div className="field"><label>Preferred contact</label><select name="preferred_contact"><option>WhatsApp</option><option>Phone</option><option>Email</option></select></div><div className="field field-full"><label>Message</label><textarea name="message" rows={4}/></div><div className="field field-full"><button className="button button-blue" type="submit">Submit rental request</button></div></form></div></section></SiteShell>}
