import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "@/components/site-shell";
import { getVehicleBySlug } from "@/lib/data";
import { formatCurrency } from "@/lib/utils";

type Params=Promise<{slug:string}>;
export async function generateMetadata({params}:{params:Params}):Promise<Metadata>{const {slug}=await params;const vehicle=await getVehicleBySlug(slug);return{title:vehicle?`Hire ${vehicle.make} ${vehicle.model}`:"Rental not found"};}
export default async function RentalDetailPage({params}:{params:Params}){const {slug}=await params;const vehicle=await getVehicleBySlug(slug);if(!vehicle||vehicle.listing_type!=="rental")notFound();const cover=vehicle.images?.find(i=>i.is_cover)??vehicle.images?.[0];return <SiteShell><section className="section"><div className="container"><Link href="/rentals">← Back to rentals</Link><div className="detail-grid" style={{marginTop:20}}><div><div className="detail-image"><img src={cover?.image_url||"/car.svg"} alt={`${vehicle.make} ${vehicle.model}`}/></div><div className="panel panel-pad" style={{marginTop:20}}><h2>Rental overview</h2><p>{vehicle.description}</p><ul className="feature-list">{vehicle.features.map(feature=><li key={feature}>✓ {feature}</li>)}</ul></div></div><aside className="panel panel-pad"><span className="pill pill-blue">Self-drive</span><h1>{vehicle.year} {vehicle.make} {vehicle.model}</h1><p className="price text-blue">{formatCurrency(vehicle.daily_rate)}/day</p><p className="meta">Weekly {formatCurrency(vehicle.weekly_rate)} • Monthly {formatCurrency(vehicle.monthly_rate)}</p><div className="spec-grid"><div className="spec"><small>Seats</small><strong>{vehicle.seats??5}</strong></div><div className="spec"><small>Fuel</small><strong>{vehicle.fuel_type}</strong></div><div className="spec"><small>Transmission</small><strong>{vehicle.transmission}</strong></div><div className="spec"><small>Location</small><strong>{vehicle.location}</strong></div></div><Link href={`/rentals/request?vehicle=${vehicle.id}`} className="button button-blue" style={{width:"100%",marginTop:22}}>Request this rental</Link><Link href="/help" className="button button-outline" style={{width:"100%",marginTop:10}}>Read rental terms</Link></aside></div></div></section></SiteShell>}
